DROP TABLE IF EXISTS app_ads;
DROP TABLE IF EXISTS app_contents;
DROP TABLE IF EXISTS apps;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS public.users;