version: "3.9"
services:
  app:
    build: .
    restart: always
    environment:
      - ENV=production
    ports:
      - "3002:5000"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres"
    restart: always
    environment:
      PGUSER: ${DB_USERNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_OPEN_PORT}:5432"
      - "5432"
    volumes:
      - ${DB_LOCAL_STORAGE}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./migration:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
        "up"
      ]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "${NSQLOOKUPD_OPEN_PORT}:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    ports:
      - "${NSQD_TCP_OPEN_PORT}:4150" # so consumer can connect to this nsqd.
      - "4150"
      - "4151"
    volumes:
      - ${NSQ_LOCAL_STORAGE}:/data
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "${NSQADMIN_OPEN_PORT}:4171"
  redis:
    image: "redis:alpine"
    volumes:
      - ${REDIS_LOCAL_STORAGE}:/data