version: "3.9"
services:
  app:
    image: "ibrahimsyah/dynapgen:latest"
    environment:
      ENV: production
    ports:
      - "3002:5000"
    volumes:
      - ./:/usr/src/app/
  redis:
    image: "redis:alpine"