version: "3.9"
services:
  app:
    image: "ibrahimsyah/dynapgen:latest"
    environment:
      ENV: production
      GITHUB_CLIENT_KEY: ${GITHUB_CLIENT_KEY}
    ports:
      - "3002:5000"
    volumes:
      - ./:/usr/src/app/
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_OPEN_PORT}:5432"
      - "5432:5432"
    volumes:
      - ${DB_LOCAL_STORAGE}:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"